import json

list = [{'bib': {'cites': '2049',
         'title': 'Recent developments in modeling preferences: Uncertainty '
                  'and ambiguity',
         'year': '1992'},
 'filled': False,
 'id_citations': 'SDlCXgwAAAAJ:9Nmd_mFXekcC',
 'source': 'citations'}, {'bib': {'cites': '1428', 'title': 'Rationales entscheiden', 'year': '2013'},
 'filled': False,
 'id_citations': 'SDlCXgwAAAAJ:CdxZDUztZiMC',
 'source': 'citations'}, {'bib': {'cites': '1090',
         'title': 'The disposition effect in securities trading: An '
                  'experimental analysis',
         'year': '1998'},
 'filled': False,
 'id_citations': 'SDlCXgwAAAAJ:FAceZFleit8C',
 'source': 'citations'}, {'bib': {'cites': '843',
         'title': 'The curse of knowledge in economic settings: An '
                  'experimental analysis',
         'year': '1989'},
 'filled': False,
 'id_citations': 'SDlCXgwAAAAJ:RoXSNcbkSzsC',
 'source': 'citations'}, {'bib': {'cites': '807',
         'title': 'Overconfidence and trading volume',
         'year': '2007'},
 'filled': False,
 'id_citations': 'SDlCXgwAAAAJ:2VqYfGB8ITEC',
 'source': 'citations'}, {'bib': {'cites': '801', 'title': 'Bankbetriebslehre', 'year': '1998'},
 'filled': False,
 'id_citations': 'SDlCXgwAAAAJ:1qzjygNMrQYC',
 'source': 'citations'}, {'bib': {'cites': '770',
         'title': 'Informational efficiency of credit default swap and stock '
                  'markets: The impact of credit rating announcements',
         'year': '2004'},
 'filled': False,
 'id_citations': 'SDlCXgwAAAAJ:rO6llkc54NcC',
 'source': 'citations'}, {'bib': {'cites': '613',
         'title': 'The co‐movement of credit default swap, bond and stock '
                  'markets: An empirical analysis',
         'year': '2009'},
 'filled': False,
 'id_citations': 'SDlCXgwAAAAJ:1taIhTC69MYC',
 'source': 'citations'}, {'bib': {'cites': '553',
         'title': 'Loan growth and riskiness of banks',
         'year': '2010'},
 'filled': False,
 'id_citations': 'SDlCXgwAAAAJ:ClCfbGk0d_YC',
 'source': 'citations'}, {'bib': {'cites': '511',
         'title': 'The role of non-financial factors in internal credit '
                  'ratings',
         'year': '2005'},
 'filled': False,
 'id_citations': 'SDlCXgwAAAAJ:tH6gc1N1XXoC',
 'source': 'citations'}, {'bib': {'cites': '476',
         'title': 'Decision making with incomplete information',
         'year': '1987'},
 'filled': False,
 'id_citations': 'SDlCXgwAAAAJ:_Qo2XoVZTnwC',
 'source': 'citations'}, {'bib': {'cites': '473',
         'title': 'Behavioral influences on weight judgments in multiattribute '
                  'decision making',
         'year': '1993'},
 'filled': False,
 'id_citations': 'SDlCXgwAAAAJ:7Hz3ACDFbsoC',
 'source': 'citations'}, {'bib': {'cites': '344',
         'title': 'Bank behavior based on internal credit ratings of borrowers',
         'year': '1998'},
 'filled': False,
 'id_citations': 'SDlCXgwAAAAJ:XD-gHx7UXLsC',
 'source': 'citations'}, {'bib': {'cites': '331',
         'title': 'Choice-based elicitation and decomposition of decision '
                  'weights for gains and losses under uncertainty',
         'year': '2005'},
 'filled': False,
 'id_citations': 'SDlCXgwAAAAJ:g5m5HwL7SMYC',
 'source': 'citations'}, {'bib': {'cites': '304', 'title': 'Risk-value models', 'year': '1993'},
 'filled': False,
 'id_citations': 'SDlCXgwAAAAJ:e_rmSamDkqQC',
 'source': 'citations'}, {'bib': {'cites': '298',
         'title': 'What determines the shape of the probability weighting '
                  'function under uncertainty?',
         'year': '2001'},
 'filled': False,
 'id_citations': 'SDlCXgwAAAAJ:8k81kl-MbHgC',
 'source': 'citations'}, {'bib': {'cites': '289',
         'title': 'Ambiguity aversion, comparative ignorance, and decision '
                  'context',
         'year': '2002'},
 'filled': False,
 'id_citations': 'SDlCXgwAAAAJ:AHdEip9mkN0C',
 'source': 'citations'}, {'bib': {'cites': '282',
         'title': 'Home bias in international stock return expectations',
         'year': '2000'},
 'filled': False,
 'id_citations': 'SDlCXgwAAAAJ:6_hjMsCP8ZoC',
 'source': 'citations'}, {'bib': {'cites': '262',
         'title': 'Generally accepted rating principles: A primer',
         'year': '2001'},
 'filled': False,
 'id_citations': 'SDlCXgwAAAAJ:hFOr9nPyWt4C',
 'source': 'citations'}, {'bib': {'cites': '249',
         'title': 'The effects of splitting attributes on weights in '
                  'multiattribute utility measurement',
         'year': '1988'},
 'filled': False,
 'id_citations': 'SDlCXgwAAAAJ:86PQX7AUzd4C',
 'source': 'citations'}, {'bib': {'cites': '245', 'title': 'Rational decision making', 'year': '2009'},
 'filled': False,
 'id_citations': 'SDlCXgwAAAAJ:F2UWTTQJPOcC',
 'source': 'citations'}, {'bib': {'cites': '244',
         'title': 'Reference-point formation and updating',
         'year': '2011'},
 'filled': False,
 'id_citations': 'SDlCXgwAAAAJ:umqufdRvDiIC',
 'source': 'citations'}, {'bib': {'cites': '241',
         'title': 'Effects of ambiguity in market experiments',
         'year': '1993'},
 'filled': False,
 'id_citations': 'SDlCXgwAAAAJ:ufrVoPGSRksC',
 'source': 'citations'}, {'bib': {'cites': '238',
         'title': 'Contrarian and momentum strategies in Germany',
         'year': '1999'},
 'filled': False,
 'id_citations': 'SDlCXgwAAAAJ:5awf1xo2G04C',
 'source': 'citations'}, {'bib': {'cites': '225',
         'title': 'How riskily do I invest? The role of risk attitudes, risk '
                  'perceptions, and overconfidence',
         'year': '2010'},
 'filled': False,
 'id_citations': 'SDlCXgwAAAAJ:QIV2ME_5wuYC',
 'source': 'citations'}, {'bib': {'cites': '222',
         'title': 'The effect of attribute ranges on weights in multiattribute '
                  'utility measurements',
         'year': '1993'},
 'filled': False,
 'id_citations': 'SDlCXgwAAAAJ:uVUOdF_882EC',
 'source': 'citations'}, {'bib': {'cites': '220',
         'title': 'Which past returns affect trading volume?',
         'year': '2009'},
 'filled': False,
 'id_citations': 'SDlCXgwAAAAJ:t7zJ5fGR-2UC',
 'source': 'citations'}, {'bib': {'cites': '212',
         'title': 'An empirical study on intertemporal decision making under '
                  'risk',
         'year': '1997'},
 'filled': False,
 'id_citations': 'SDlCXgwAAAAJ:PaBasH6fAo0C',
 'source': 'citations'}, {'bib': {'cites': '206',
         'title': 'Communicating asset risk: How name recognition and the '
                  'format of historic volatility information affect risk '
                  'perception and investment decisions',
         'year': '2005'},
 'filled': False,
 'id_citations': 'SDlCXgwAAAAJ:dfsIfKJdRG4C',
 'source': 'citations'}, {'bib': {'cites': '195',
         'title': 'Recent developments in modelling preferences under risk',
         'year': '1987'},
 'filled': False,
 'id_citations': 'SDlCXgwAAAAJ:NaGl4SEjCO4C',
 'source': 'citations'}, {'bib': {'cites': '192',
         'title': 'Who takes risks when and why: Determinants of changes in '
                  'investor risk taking',
         'year': '2013'},
 'filled': False,
 'id_citations': 'SDlCXgwAAAAJ:4vMrXwiscB8C',
 'source': 'citations'}, {'bib': {'cites': '192',
         'title': 'Credit line usage, checking account activity, and default '
                  'risk of bank borrowers',
         'year': '2010'},
 'filled': False,
 'id_citations': 'SDlCXgwAAAAJ:uLbwQdceFCQC',
 'source': 'citations'}, {'bib': {'cites': '186', 'title': 'Behavioral finance', 'year': '2004'},
 'filled': False,
 'id_citations': 'SDlCXgwAAAAJ:gKiMpY-AVTkC',
 'source': 'citations'}, {'bib': {'cites': '186',
         'title': 'Prospect theory, mental accounting, and differences in '
                  'aggregated and segregated evaluation of lottery portfolios',
         'year': '2001'},
 'filled': False,
 'id_citations': 'SDlCXgwAAAAJ:WHdLCjDvYFkC',
 'source': 'citations'}, {'bib': {'cites': '176',
         'title': 'How do prior outcomes affect risk attitude? Comparing '
                  'escalation of commitment and the house-money effect',
         'year': '2005'},
 'filled': False,
 'id_citations': 'SDlCXgwAAAAJ:jU7OWUQzBzMC',
 'source': 'citations'}, {'bib': {'cites': '173',
         'title': 'Recovery rates of commercial lending: Empirical evidence '
                  'for German companies',
         'year': '2009'},
 'filled': False,
 'id_citations': 'SDlCXgwAAAAJ:uWQEDVKXjbEC',
 'source': 'citations'}, {'bib': {'cites': '168',
         'title': 'Risk as a primitive: A survey of measures of perceived risk',
         'year': '1997'},
 'filled': False,
 'id_citations': 'SDlCXgwAAAAJ:XoXfffV-tXoC',
 'source': 'citations'}, {'bib': {'cites': '164',
         'title': 'Investment decisions and time horizon: Risk perception and '
                  'risk behavior in repeated gambles',
         'year': '2005'},
 'filled': False,
 'id_citations': 'SDlCXgwAAAAJ:HGTzPopzzJcC',
 'source': 'citations'}, {'bib': {'cites': '163',
         'title': 'The role of experience sampling and graphical displays on '
                  "one's investment risk appetite",
         'year': '2013'},
 'filled': False,
 'id_citations': 'SDlCXgwAAAAJ:-mN3Mh-tlDkC',
 'source': 'citations'}, {'bib': {'cites': '151',
         'title': 'A new method of scenario analysis for strategic planning',
         'year': '1988'},
 'filled': False,
 'id_citations': 'SDlCXgwAAAAJ:oi2SiIJ9l4AC',
 'source': 'citations'}, {'bib': {'cites': '149',
         'title': 'Overconfidence of professionals and lay men: Individual '
                  'differences within and between tasks?',
         'year': '2005'},
 'filled': False,
 'id_citations': 'SDlCXgwAAAAJ:OcBU2YAGkTUC',
 'source': 'citations'}, {'bib': {'cites': '149',
         'title': 'Information aggregation with random ordering: Cascades and '
                  'overconfidence',
         'year': '2003'},
 'filled': False,
 'id_citations': 'SDlCXgwAAAAJ:pyW8ca7W8N0C',
 'source': 'citations'}, {'bib': {'cites': '144',
         'title': 'Number of bank relationships: An indicator of competition, '
                  'borrower quality, or just size?',
         'year': '2000'},
 'filled': False,
 'id_citations': 'SDlCXgwAAAAJ:roLk4NBRz8UC',
 'source': 'citations'}, {'bib': {'cites': '127',
         'title': 'How do banks determine capital? Evidence from Germany',
         'year': '2008'},
 'filled': False,
 'id_citations': 'SDlCXgwAAAAJ:Ehil0879vHcC',
 'source': 'citations'}, {'bib': {'cites': '125',
         'title': 'A method of multiattribute decision making with incomplete '
                  'information',
         'year': '1985'},
 'filled': False,
 'id_citations': 'SDlCXgwAAAAJ:MpfHP-DdYjUC',
 'source': 'citations'}, {'bib': {'cites': '124',
         'title': 'Financial literacy and mutual fund investments: who buys '
                  'actively managed funds?',
         'year': '2010'},
 'filled': False,
 'id_citations': 'SDlCXgwAAAAJ:ALROH1vI_8AC',
 'source': 'citations'}, {'bib': {'cites': '117',
         'title': 'Willingness-to-pay and willingness-to-accept for risky and '
                  'ambiguous lotteries',
         'year': '1995'},
 'filled': False,
 'id_citations': 'SDlCXgwAAAAJ:nrtMV_XWKgEC',
 'source': 'citations'}, {'bib': {'cites': '115',
         'title': 'Hindsight bias, risk perception, and investment performance',
         'year': '2009'},
 'filled': False,
 'id_citations': 'SDlCXgwAAAAJ:yB1At4FlUx8C',
 'source': 'citations'}, {'bib': {'cites': '112',
         'title': 'Myopic prospect theory vs. myopic loss aversion: how '
                  'general is the phenomenon?',
         'year': '2005'},
 'filled': False,
 'id_citations': 'SDlCXgwAAAAJ:jE2MZjpN3IcC',
 'source': 'citations'}, {'bib': {'cites': '108',
         'title': 'Hyperbolic discounting models in prescriptive theory of '
                  'intertemporal choice',
         'year': '1995'},
 'filled': False,
 'id_citations': 'SDlCXgwAAAAJ:5ugPr518TE4C',
 'source': 'citations'}]

x = { 'publications' : list}
st = json.dumps(x)
print(st)